### PR TITLE
added ClientMessage and Bits

### PR DESCRIPTION
**Pull request by bilalyasar**
client message is written in TypeScript

### CODE REVIEW

**Comment by asimarslan** [comment]
I think we shouldn't commit the compiled codes.

**Comment by bilalyasar** [comment]
yes, updated.

**Comment by mustafaiman** [comment]
I guess `.map` files should be omitted too?

**Comment by gAmUssA** [comment]
let's follow M$ directory structure. `d.ts` files should be placed in `typings` folder.

Here is a reference project https://github.com/Microsoft/vscode/tree/master/src

**Comment by bilalyasar** [comment]
i updated PR.

**Comment by mustafaiman** [comment]
:+1:

**Pull request merged**
